name: Run Updater Monthly

on:
    - workflow_dispatch
    schedule:
        - cron: '0 * * * *' 
    

permissions:
    checks: write
    actions: write
        
jobs:
    run-updater-python-module:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
        uses: actions/checkout@v4
        - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.13' 
        - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
                
        - name: Run updater module
        run: python -m update_data.py
