name: Run Monthly Updater 


on: 
  schedule:
    - cron: '0 0 1 * *' 
  workflow_dispatch:

permissions:
    checks: write
    actions: write
    contents: write
jobs:
  run-data-updater-python-module:
    runs-on: ubuntu-latest

    steps:

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13' 
        
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run updater module
      run: python -m update_data

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add data/*.csv # Add all CSV files in the data folder
        git commit -m "Update CSV files with new data"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        
