name: Run Updater Monthly

on:
  schedule:
    - cron: '0 * * * *' # At midnight on the first day of every month (UTC)

jobs:
  run-updater-python-module:
    runs-on: ubuntu-latest

    steps:

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13' # Specify your Python version
        
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run updater module
      run: python -m update_data.py
